"""Added client and notes tables

Revision ID: 8b4d17ecdf9d
Revises: cbb40460a2b0
Create Date: 2025-02-17 19:29:52.536599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4d17ecdf9d'
down_revision: Union[str, None] = 'cbb40460a2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
